name: Build and test Nim

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: jiro4989/setup-nim-actions@v1
    - name: Run build test
      run: nimble install nimjson

