name: build

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        version:
          - 1.0.0
          - stable
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        nim-version: ${{ matrix.version }}
    - name: Print Nim version
      run: nim -v
    - name: Print Nimble version
      run: nimble -v
    - name: Run build test
      run: nimble install -Y nimjson
    - name: Run command
      run: nimjson -h

  test_v1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-stable
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1
    - name: Print Nim version
      run: nim -v
    - name: Print Nimble version
      run: nimble -v
    - name: Run build test
      run: nimble install -Y nimjson
    - name: Run command
      run: nimjson -h

  test_devel:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: devel
    - name: Print Nim version
      run: nim -v
    - name: Print Nimble version
      run: nimble -v
    - name: Run build test
      run: nimble install -Y nimjson
    - name: Run command
      run: nimjson -h

  test_devel_latest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-devel-latest
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-stable
    - uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 'devel --latest'
    - name: Print Nim version
      run: nim -v
    - name: Print Nimble version
      run: nimble -v
    - name: Run build test
      run: nimble install -Y nimjson
    - name: Run command
      run: nimjson -h

