name: build

on: [push]

jobs:
  skip:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Skip job"

  before:
    runs-on: ubuntu-latest
    if: "! contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - run: echo "not contains '[skip ci]'"

  test:
    runs-on: ${{ matrix.os }}
    needs: before
    strategy:
      matrix:
        os:
          - macOS-latest
        count:
          - 1
          - 2
          - 3
          - 4
          - 5
          - 6
          - 7
          - 8
          - 9
          - 10
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        with:
          nim-version: 'devel'
        continue-on-error: true
